#pragma once
enum Ease {
	EASE_IN_CUBIC, EASE_OUT_CUBIC, CONSTANT, EASE_IN_ELASTIC, EASE_OUT_ELASTIC, EASE_IN_HOLD, EASE_IN_QUAD, EASE_OUT_QUAD, EASE_IN_OUT_QUAD, EASE_OUT_CIRC, IN_OUT, EASE_IN_QUINT, EASE_OUT_QUINT
};